/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant.capa1_presentacion;

import static java.awt.Frame.MAXIMIZED_BOTH;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import restaurant.capa2_aplicacion.GestionarReporteServicio;
import restaurant.capa3_dominio.IniciarSesion;
import restaurant.capa3_dominio.TipoUsuario;

/**
 *
 * @author Antonio AB
 */
public class FormMenu extends javax.swing.JFrame {

    private boolean estadoBotonReporte = false;
    private int PosicionMouse;
    private boolean minimiza = false;
    private FormGestionarUsuario gestionarUsuario;
    private GestionarReporteServicio gestionarReporteServicio;

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        asignarLookandfeel();
        initComponents();

        this.setLocationRelativeTo(this);
        this.setExtendedState(MAXIMIZED_BOTH);

        lblposiciones.setVisible(false);
        lblposciciony.setVisible(false);
        gestionarReporteServicio = new GestionarReporteServicio();
        validadUsuario(IniciarSesion.getUsuario().getTipoUsuario().getTipoUsuarioNombre());
    }

    void validadUsuario(String tipoUsuario) {
        if (tipoUsuario.equals(TipoUsuario.Tipo_mozo)) {
            btnGestionarMesa.setEnabled(false);
            btnGestionarProducto.setEnabled(false);
            btnGestionarTipoProducto.setEnabled(false);
            btnGestionarUsuario.setEnabled(false);
            btnGestionarTipoUsuario.setEnabled(false);
            btnOtros.setEnabled(false);
            btnPermisos.setEnabled(false);
            btnGestionarMesa.setEnabled(false);
        }
    }

    private void asignarLookandfeel() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuReportes = new rojerusan.RSPopuMenu();
        panelOpcionesReportes = new javax.swing.JPanel();
        btnGestionarReporteCliente = new rojerusan.RSButtonPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEliminar = new rojerusan.RSButtonPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnVisualizarPedidos = new rojerusan.RSButtonPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCerrar = new rojerusan.RSButtonMetro();
        btnMinimizar = new rojerusan.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        jPanel3 = new javax.swing.JPanel();
        rSLabelVerticalI1 = new rojerusan.RSLabelVerticalI();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        btnGestionarProducto = new rojerusan.RSButtonIconI();
        btnInicio = new rojerusan.RSButtonIconI();
        btnGestionarCliente = new rojerusan.RSButtonIconI();
        jSeparator3 = new javax.swing.JSeparator();
        btnGestionarMesa = new rojerusan.RSButtonIconI();
        btnGestionarTipoProducto = new rojerusan.RSButtonIconI();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        rSLabelVerticalI2 = new rojerusan.RSLabelVerticalI();
        btnRegistarPedido = new rojerusan.RSButtonIconI();
        jSeparator6 = new javax.swing.JSeparator();
        rSLabelVerticalI3 = new rojerusan.RSLabelVerticalI();
        btnReporte = new rojerusan.RSButtonIconI();
        jSeparator4 = new javax.swing.JSeparator();
        rSLabelVerticalI4 = new rojerusan.RSLabelVerticalI();
        btnOtros = new rojerusan.RSButtonIconI();
        btnPermisos = new rojerusan.RSButtonIconI();
        jSeparator8 = new javax.swing.JSeparator();
        rSLabelVerticalI5 = new rojerusan.RSLabelVerticalI();
        btnAyuda = new rojerusan.RSButtonIconI();
        btnAcercaDe = new rojerusan.RSButtonIconI();
        jSeparator9 = new javax.swing.JSeparator();
        btnGestionarUsuario = new rojerusan.RSButtonIconI();
        btnGestionarTipoUsuario = new rojerusan.RSButtonIconI();
        escritorio = new restaurant.capa1_presentacion.util.Escritorio();
        lblFechaActual = new javax.swing.JLabel();
        lblFechaActual1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblposiciones = new javax.swing.JLabel();
        lblposciciony = new javax.swing.JLabel();

        btnGestionarReporteCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionarReporteCliente.setColorHover(new java.awt.Color(253, 173, 1));
        btnGestionarReporteCliente.setColorNormal(new java.awt.Color(255, 255, 255));
        btnGestionarReporteCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGestionarReporteClienteMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 112, 192));
        jLabel8.setText("Reporte Cliente");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/report.png"))); // NOI18N

        javax.swing.GroupLayout btnGestionarReporteClienteLayout = new javax.swing.GroupLayout(btnGestionarReporteCliente);
        btnGestionarReporteCliente.setLayout(btnGestionarReporteClienteLayout);
        btnGestionarReporteClienteLayout.setHorizontalGroup(
            btnGestionarReporteClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGestionarReporteClienteLayout.createSequentialGroup()
                .addGap(0, 85, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnGestionarReporteClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnGestionarReporteClienteLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );
        btnGestionarReporteClienteLayout.setVerticalGroup(
            btnGestionarReporteClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(btnGestionarReporteClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setColorHover(new java.awt.Color(253, 173, 1));
        btnEliminar.setColorNormal(new java.awt.Color(255, 255, 255));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 112, 192));
        jLabel10.setText("Otros");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/otro.png"))); // NOI18N

        javax.swing.GroupLayout btnEliminarLayout = new javax.swing.GroupLayout(btnEliminar);
        btnEliminar.setLayout(btnEliminarLayout);
        btnEliminarLayout.setHorizontalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnEliminarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(208, Short.MAX_VALUE)))
        );
        btnEliminarLayout.setVerticalGroup(
            btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(btnEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVisualizarPedidos.setBackground(new java.awt.Color(255, 255, 255));
        btnVisualizarPedidos.setColorHover(new java.awt.Color(253, 173, 1));
        btnVisualizarPedidos.setColorNormal(new java.awt.Color(255, 255, 255));
        btnVisualizarPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVisualizarPedidosMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 112, 192));
        jLabel12.setText("Vizualizar Pedidos");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/ver.png"))); // NOI18N

        javax.swing.GroupLayout btnVisualizarPedidosLayout = new javax.swing.GroupLayout(btnVisualizarPedidos);
        btnVisualizarPedidos.setLayout(btnVisualizarPedidosLayout);
        btnVisualizarPedidosLayout.setHorizontalGroup(
            btnVisualizarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVisualizarPedidosLayout.createSequentialGroup()
                .addGap(0, 85, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btnVisualizarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnVisualizarPedidosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13)
                    .addContainerGap(213, Short.MAX_VALUE)))
        );
        btnVisualizarPedidosLayout.setVerticalGroup(
            btnVisualizarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVisualizarPedidosLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btnVisualizarPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnVisualizarPedidosLayout.createSequentialGroup()
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout panelOpcionesReportesLayout = new javax.swing.GroupLayout(panelOpcionesReportes);
        panelOpcionesReportes.setLayout(panelOpcionesReportesLayout);
        panelOpcionesReportesLayout.setHorizontalGroup(
            panelOpcionesReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGestionarReporteCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
            .addComponent(btnVisualizarPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        panelOpcionesReportesLayout.setVerticalGroup(
            panelOpcionesReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesReportesLayout.createSequentialGroup()
                .addComponent(btnGestionarReporteCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVisualizarPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(68, 138, 255));

        btnCerrar.setBackground(new java.awt.Color(255, 0, 51));
        btnCerrar.setText("X");
        btnCerrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCerrar.setGrosorLinea(3);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMinimizar.setBackground(new java.awt.Color(255, 0, 51));
        btnMinimizar.setText("_");
        btnMinimizar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnMinimizar.setGrosorLinea(3);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("“SOFTWARE DE RESTAURANT CON DISEÑO ARQUITECTURAL N-CAPAS”");

        rSLabelImage1.setBackground(new java.awt.Color(255, 255, 255));
        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(rSLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 499, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(rSLabelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowBottomShadow(false);
        jPanel3.setBorder(dropShadowBorder1);

        rSLabelVerticalI1.setText("Administración");

        rSLabelImage2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/sistea.png"))); // NOI18N
        rSLabelImage2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rSLabelImage2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rSLabelImage2.setInheritsPopupMenu(false);

        btnGestionarProducto.setBackground(new java.awt.Color(238, 238, 238));
        btnGestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/gestionarproducto.png"))); // NOI18N
        btnGestionarProducto.setText("        Gestionar Producto");
        btnGestionarProducto.setColorHover(new java.awt.Color(50, 194, 77));
        btnGestionarProducto.setColorText(new java.awt.Color(123, 122, 122));
        btnGestionarProducto.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnGestionarProducto.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnGestionarProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarProductoActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(238, 238, 238));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/menu.png"))); // NOI18N
        btnInicio.setText("            MENU");
        btnInicio.setColorHover(new java.awt.Color(204, 204, 204));
        btnInicio.setColorText(new java.awt.Color(123, 122, 122));
        btnInicio.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnInicio.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.setSelected(true);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnGestionarCliente.setBackground(new java.awt.Color(238, 238, 238));
        btnGestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/gestionarcliente.png"))); // NOI18N
        btnGestionarCliente.setText("           Gestionar Cliente");
        btnGestionarCliente.setColorHover(new java.awt.Color(50, 194, 77));
        btnGestionarCliente.setColorText(new java.awt.Color(123, 122, 122));
        btnGestionarCliente.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnGestionarCliente.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGestionarCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarClienteActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(68, 138, 255));
        jSeparator3.setForeground(new java.awt.Color(68, 138, 255));

        btnGestionarMesa.setBackground(new java.awt.Color(238, 238, 238));
        btnGestionarMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/gestionarmesa.png"))); // NOI18N
        btnGestionarMesa.setText("           Gestionar Mesa");
        btnGestionarMesa.setColorHover(new java.awt.Color(50, 194, 77));
        btnGestionarMesa.setColorText(new java.awt.Color(123, 122, 122));
        btnGestionarMesa.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnGestionarMesa.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGestionarMesa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarMesaActionPerformed(evt);
            }
        });

        btnGestionarTipoProducto.setBackground(new java.awt.Color(238, 238, 238));
        btnGestionarTipoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/productotipo.png"))); // NOI18N
        btnGestionarTipoProducto.setText("           Gestionar Tipo Producto");
        btnGestionarTipoProducto.setColorHover(new java.awt.Color(50, 194, 77));
        btnGestionarTipoProducto.setColorText(new java.awt.Color(123, 122, 122));
        btnGestionarTipoProducto.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnGestionarTipoProducto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGestionarTipoProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarTipoProductoActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 200, 81));
        jSeparator2.setForeground(new java.awt.Color(0, 200, 81));

        jSeparator5.setBackground(new java.awt.Color(68, 138, 255));
        jSeparator5.setForeground(new java.awt.Color(68, 138, 255));

        rSLabelVerticalI2.setText("Procesos");

        btnRegistarPedido.setBackground(new java.awt.Color(238, 238, 238));
        btnRegistarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/pedido.png"))); // NOI18N
        btnRegistarPedido.setText("        Registrar Pedido");
        btnRegistarPedido.setColorHover(new java.awt.Color(50, 194, 77));
        btnRegistarPedido.setColorText(new java.awt.Color(123, 122, 122));
        btnRegistarPedido.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnRegistarPedido.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegistarPedido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarPedidoActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(68, 138, 255));
        jSeparator6.setForeground(new java.awt.Color(68, 138, 255));

        rSLabelVerticalI3.setText("Reportes");

        btnReporte.setBackground(new java.awt.Color(238, 238, 238));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/reportepedidos.png"))); // NOI18N
        btnReporte.setText("        Reportes");
        btnReporte.setColorHover(new java.awt.Color(50, 194, 77));
        btnReporte.setColorText(new java.awt.Color(123, 122, 122));
        btnReporte.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnReporte.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnReporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReporteMousePressed(evt);
            }
        });
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(68, 138, 255));
        jSeparator4.setForeground(new java.awt.Color(68, 138, 255));

        rSLabelVerticalI4.setText("Seguridad");

        btnOtros.setBackground(new java.awt.Color(238, 238, 238));
        btnOtros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/gestionarusuarios.png"))); // NOI18N
        btnOtros.setText("          Gestionar Otros");
        btnOtros.setColorHover(new java.awt.Color(50, 194, 77));
        btnOtros.setColorText(new java.awt.Color(123, 122, 122));
        btnOtros.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnOtros.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnOtros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtrosActionPerformed(evt);
            }
        });

        btnPermisos.setBackground(new java.awt.Color(238, 238, 238));
        btnPermisos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/gestionarpermisos.png"))); // NOI18N
        btnPermisos.setText("          Gestionar Permisos");
        btnPermisos.setColorHover(new java.awt.Color(50, 194, 77));
        btnPermisos.setColorText(new java.awt.Color(123, 122, 122));
        btnPermisos.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnPermisos.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPermisos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(68, 138, 255));
        jSeparator8.setForeground(new java.awt.Color(68, 138, 255));

        rSLabelVerticalI5.setText("Aplicación");

        btnAyuda.setBackground(new java.awt.Color(238, 238, 238));
        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/ayuda.png"))); // NOI18N
        btnAyuda.setText("          Ayuda");
        btnAyuda.setColorHover(new java.awt.Color(50, 194, 77));
        btnAyuda.setColorText(new java.awt.Color(123, 122, 122));
        btnAyuda.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnAyuda.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAyuda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        btnAcercaDe.setBackground(new java.awt.Color(238, 238, 238));
        btnAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/about.png"))); // NOI18N
        btnAcercaDe.setText("          Acerca de...");
        btnAcercaDe.setColorHover(new java.awt.Color(50, 194, 77));
        btnAcercaDe.setColorText(new java.awt.Color(123, 122, 122));
        btnAcercaDe.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnAcercaDe.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnAcercaDe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(68, 138, 255));
        jSeparator9.setForeground(new java.awt.Color(68, 138, 255));

        btnGestionarUsuario.setBackground(new java.awt.Color(238, 238, 238));
        btnGestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/mozo.png"))); // NOI18N
        btnGestionarUsuario.setText("           Gestionar Usuario");
        btnGestionarUsuario.setColorHover(new java.awt.Color(50, 194, 77));
        btnGestionarUsuario.setColorText(new java.awt.Color(123, 122, 122));
        btnGestionarUsuario.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnGestionarUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGestionarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuarioActionPerformed(evt);
            }
        });

        btnGestionarTipoUsuario.setBackground(new java.awt.Color(238, 238, 238));
        btnGestionarTipoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/capa5_imagenes/gestionarpermisos.png"))); // NOI18N
        btnGestionarTipoUsuario.setText("           Gestionar Tipo Usuario");
        btnGestionarTipoUsuario.setColorHover(new java.awt.Color(50, 194, 77));
        btnGestionarTipoUsuario.setColorText(new java.awt.Color(123, 122, 122));
        btnGestionarTipoUsuario.setColorTextHover(new java.awt.Color(123, 122, 122));
        btnGestionarTipoUsuario.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnGestionarTipoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGestionarTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarTipoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addComponent(btnInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator9)
            .addComponent(rSLabelImage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator8)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSLabelVerticalI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelVerticalI5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelVerticalI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelVerticalI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelVerticalI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionarTipoProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarMesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOtros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPermisos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addComponent(btnGestionarTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jSeparator3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGestionarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnGestionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(rSLabelImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGestionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelVerticalI1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnGestionarMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGestionarTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGestionarTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGestionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelVerticalI2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnRegistarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelVerticalI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSLabelVerticalI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSLabelVerticalI5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        escritorio.setBackground(new java.awt.Color(255, 255, 255));
        escritorio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                escritorioMouseMoved(evt);
            }
        });

        lblFechaActual.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        lblFechaActual.setForeground(new java.awt.Color(35, 114, 194));
        lblFechaActual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaActual.setText("© Derechos reservados ");

        lblFechaActual1.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        lblFechaActual1.setForeground(new java.awt.Color(35, 114, 194));
        lblFechaActual1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFechaActual1.setText("FiveCod Software 2018");

        jLabel24.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(35, 114, 194));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Versión 1.0");

        lblposiciones.setText("posicion: X");

        lblposciciony.setText("posicon : y");

        escritorio.setLayer(lblFechaActual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblFechaActual1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblposiciones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblposciciony, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaActual)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel24))
                            .addComponent(lblFechaActual1)))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(lblposiciones)
                        .addGap(62, 62, 62)
                        .addComponent(lblposciciony)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblposiciones)
                    .addComponent(lblposciciony))
                .addGap(166, 166, 166)
                .addComponent(lblFechaActual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaActual1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        if (JOptionPane.showConfirmDialog(this, "Esta a punto de\ncerrar la sesión\n¿Desea continuar?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION, 0,
                new ImageIcon(getClass().getResource(""))) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
        if (!minimiza) {
            minimiza = false;
            this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        } else {
            minimiza = true;
        }
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPermisosActionPerformed

    private void btnOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtrosActionPerformed

    }//GEN-LAST:event_btnOtrosActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        mostrarMenuReporte();

    }//GEN-LAST:event_btnReporteActionPerformed
    private void mostrarMenuReporte() {
        if (estadoBotonReporte == false) {
            this.menuReportes.add(panelOpcionesReportes);
            this.menuReportes.setVisible(true);
            this.menuReportes.setLocation(lblposiciones.getX(), lblposciciony.getY());
            estadoBotonReporte = true;
        } else {
            this.menuReportes.setVisible(false);
            estadoBotonReporte = false;
        }
    }

    private void btnRegistarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarPedidoActionPerformed
        try {
            FormRegistrarPedido j = new FormRegistrarPedido(this, true);
            j.setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnRegistarPedidoActionPerformed

    private void btnGestionarTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarTipoProductoActionPerformed
        try {
            FormGestionarTipoProducto d = new FormGestionarTipoProducto(this, true);
            d.setVisible(true);// TODO add your handling code here: 
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnGestionarTipoProductoActionPerformed

    private void btnGestionarMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarMesaActionPerformed

        FormGestionarMesa d = new FormGestionarMesa(this, true);
        d.setVisible(true);// TODO add your handling code here: 

    }//GEN-LAST:event_btnGestionarMesaActionPerformed

    private void btnGestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarClienteActionPerformed
        FormGestionarCliente d = new FormGestionarCliente(this, true, FormGestionarCliente.TIPO_ADMINISTRADOR);
        d.setVisible(true);
    }//GEN-LAST:event_btnGestionarClienteActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed

    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnGestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarProductoActionPerformed
        try {
            FormGestionarProducto gestionarUsuario = new FormGestionarProducto(this, true);

            gestionarUsuario.setVisible(true);
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnGestionarProductoActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        FormAcercaDe j = new FormAcercaDe(this, true);
        j.setVisible(true);
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private void btnGestionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuarioActionPerformed
        try {
            FormGestionarUsuario gestionarMozo = new FormGestionarUsuario(this, true);

            gestionarMozo.setVisible(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnGestionarUsuarioActionPerformed

    private void btnGestionarReporteClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionarReporteClienteMousePressed
        this.menuReportes.setVisible(false);
        FormGestionarReporteCliente formGestionarReporteCliente = new FormGestionarReporteCliente(this, true);
        formGestionarReporteCliente.setVisible(true);

//        try {
//
//            JasperPrint print = gestionarReporteServicio.mostrartReporte();
//            JasperViewer view = new JasperViewer(print, false);
//            view.setTitle("Reporte de Cliente");
//            view.setVisible(true);
//            this.menuReportes.setVisible(false);
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
//        }
    }//GEN-LAST:event_btnGestionarReporteClienteMousePressed

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed

    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnVisualizarPedidosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVisualizarPedidosMousePressed
        this.menuReportes.setVisible(false);
        FormGestionarMesaPanoramica formGestionarMesaPanoramica = new FormGestionarMesaPanoramica(this, true, FormGestionarMesaPanoramica.DE_PRINCIPAL);
        formGestionarMesaPanoramica.setVisible(true);

    }//GEN-LAST:event_btnVisualizarPedidosMousePressed

    private void btnReporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMousePressed

    }//GEN-LAST:event_btnReporteMousePressed

    private void escritorioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escritorioMouseMoved

    }//GEN-LAST:event_escritorioMouseMoved

    private void btnGestionarTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarTipoUsuarioActionPerformed
        try {
            FormGestionarTipoUsuario gestionarMozo = new FormGestionarTipoUsuario(this, true);
            gestionarMozo.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGestionarTipoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI btnAcercaDe;
    private rojerusan.RSButtonIconI btnAyuda;
    private rojerusan.RSButtonMetro btnCerrar;
    private rojerusan.RSButtonPane btnEliminar;
    private rojerusan.RSButtonIconI btnGestionarCliente;
    private rojerusan.RSButtonIconI btnGestionarMesa;
    private rojerusan.RSButtonIconI btnGestionarProducto;
    private rojerusan.RSButtonPane btnGestionarReporteCliente;
    private rojerusan.RSButtonIconI btnGestionarTipoProducto;
    private rojerusan.RSButtonIconI btnGestionarTipoUsuario;
    private rojerusan.RSButtonIconI btnGestionarUsuario;
    private rojerusan.RSButtonIconI btnInicio;
    private rojerusan.RSButtonMetro btnMinimizar;
    private rojerusan.RSButtonIconI btnOtros;
    private rojerusan.RSButtonIconI btnPermisos;
    private rojerusan.RSButtonIconI btnRegistarPedido;
    private rojerusan.RSButtonIconI btnReporte;
    private rojerusan.RSButtonPane btnVisualizarPedidos;
    private restaurant.capa1_presentacion.util.Escritorio escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblFechaActual;
    private javax.swing.JLabel lblFechaActual1;
    private javax.swing.JLabel lblposciciony;
    private javax.swing.JLabel lblposiciones;
    private rojerusan.RSPopuMenu menuReportes;
    private javax.swing.JPanel panelOpcionesReportes;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private rojerusan.RSLabelVerticalI rSLabelVerticalI1;
    private rojerusan.RSLabelVerticalI rSLabelVerticalI2;
    private rojerusan.RSLabelVerticalI rSLabelVerticalI3;
    private rojerusan.RSLabelVerticalI rSLabelVerticalI4;
    private rojerusan.RSLabelVerticalI rSLabelVerticalI5;
    // End of variables declaration//GEN-END:variables
}
